### ISSUE TITLE
theme display issues

### ISSUE THREAD

**Issue by tinho** [ptibogxiv/ptibogxivtheme#1]
Hello, first of all thanks and great job, I have problems to see the theme in a new installation, both of dolibar 17 and of wordpress 6.1.1,
I have tried with the version of dolibarr stable 16.3 to beta 17 and wordpress from 5.9.5 to the current 6.1.1, with the stable versions of all doliconnect, doliconnector and ptibogxivtheme, always have same error in wordpress theme,      

HTTP redirect status code must be a redirection code, 3xx.

Could you guide me where I can have the error?
the dolibarr and the wordpress communicate well and it gives me as connected, in wordpress it tells me:

Status Dolibarr
Status: 200
Version: 17.0.0
Access Locked: 0

 and API rest in dolibarr works well

thanks in advance

**Comment by ptibogxiv** [comment]
hi have you activate php error display ?

you can try to see transients with transients manager ?

**Comment by tinho** [comment]
when active php debug in wordpress --> doliconnect --> adjust  see:

Notice: Undefined index: doliaccount in \wp-content\plugins\doliconnect\admin\admin.php on line 278
Notice: Undefined index: dolicart in \wp-content\plugins\doliconnect\admin\admin.php on line 284
Notice: Undefined index: dolitos in\wp-content\plugins\doliconnect\admin\admin.php on line 285
Notice: Undefined index: wp_page_for_privacy_policy in \wp-content\plugins\doliconnect\admin\admin.php on line 290
Notice: Undefined index: dolishop in \wp-content\plugins\doliconnect\admin\admin.php on line 291
Notice: Undefined index: dolifaq in \wp-content\plugins\doliconnect\admin\admin.php on line 292
Notice: Undefined index: dolishipping in \wp-content\plugins\doliconnect\admin\admin.php on line 293
Notice: Undefined index: dolisupplier in \wp-content\plugins\doliconnect\admin\admin.php on line 296
Notice: Undefined index: dolicontact in \wp-content\plugins\doliconnect\admin\admin.php on line 297

I try to disable it in admin.php to test it, notice disappears, but on the web page it continues to show itself 
HTTP redirect status code must be a redirection code, 3xx.
any ideas?

**Comment by ptibogxiv** [comment]
have yous et some page ?

i will close this issue because it is about doliconnect and not ptibogxivtheme
