### ISSUE TITLE
The cart can icon does not appear.

### ISSUE THREAD

**Issue by MatthewWeb** [ptibogxiv/ptibogxivtheme#2]
The cart can icon does not appear.
Error "'.(!empty(doliconnector( null, 'fk_order_nb_item'))?doliconnector( null, 'fk_order_nb_item'):'0').'', 'a', 'nav-item'); ?>"
Apache2,php8.2 or php7.4 or php8.3
doliconnect 8.0.1
doliconnector 18.03
ptibogxivtheme 8.0.1
![Снимок экрана_20240407_114029](https://github.com/ptibogxiv/ptibogxivtheme/assets/56957860/253cbe1b-abdd-4998-886b-5d3a342eb52f)

**Comment by ptibogxiv** [comment]
maybe some Javascript bug on your wordpress, this button is made with AJAX

i need more debug information for fix it

**Comment by MatthewWeb** [comment]
[Sun Apr 07 13:41:58.657730 2024] [php:error] [pid 9087] [client 95.142.38.152:40209] PHP Parse error:  Unmatched '}' in /var/www/html/site.domain/wp-content/themes/ptibogxivtheme-8.0.0/footer.php on line 100

**Comment by ptibogxiv** [comment]
you have some mistakes with javascript it is the same bug. pb with your javascript and ajax

 without more information on you installation i can't fix it. I need the debug on your internet navigator

**Comment by MatthewWeb** [comment]
![Uploading Снимок экрана_20240407_143731.png…]()
[all.txt](https://github.com/ptibogxiv/ptibogxivtheme/files/14896934/all.txt)
[jquery.min.txt](https://github.com/ptibogxiv/ptibogxivtheme/files/14896935/jquery.min.txt)
[jquery-migrate.min.txt](https://github.com/ptibogxiv/ptibogxivtheme/files/14896936/jquery-migrate.min.txt)
[wp-emoji-release.min.txt](https://github.com/ptibogxiv/ptibogxivtheme/files/14896937/wp-emoji-release.min.txt)
There are no errors in the debugger. Maybe I'm looking in the wrong place.

**Comment by MatthewWeb** [comment]
<font size="1">
Call Stack
--

1 | 0.0294 | 362376 | {main}(  ) | .../index.php:0
2 | 0.0418 | 362760 | require( '/var/www/html/kigl.site/wp-blog-header.php ) | .../index.php:17
3 | 0.7501 | 3838992 | require_once( '/var/www/html/kigl.site/wp-includes/template-loader.php ) | .../wp-blog-header.php:19
4 | 0.7567 | 3906696 | include( '/var/www/html/kigl.site/wp-content/themes/ptibogxivtheme-8.0.0/page.php ) | .../template-loader.php:106
5 | 0.7999 | 4400296 | get_template_part( $slug = 'loops/content', $name = 'page', $args = ??? ) | .../page.php:24
6 | 0.7999 | 4400664 | locate_template( $template_names = [0 => 'loops/content-page.php', 1 => 'loops/content.php'], $load = TRUE, $load_once = FALSE, $args = [] ) | .../general-template.php:206
7 | 0.8001 | 4400776 | load_template( $_template_file = '/var/www/html/kigl.site/wp-content/themes/ptibogxivtheme-8.0.0/loops/content-page.php', $load_once = FALSE, $args = [] ) | .../template.php:745
8 | 0.8006 | 4401304 | require( '/var/www/html/kigl.site/wp-content/themes/ptibogxivtheme-8.0.0/loops/content-page.php ) | .../template.php:812
9 | 0.8022 | 4417008 | the_content( $more_link_text = ???, $strip_teaser = ??? ) | .../content-page.php:12
10 | 0.8024 | 4417040 | apply_filters( $hook_name = 'the_content', $value = '' ) | .../post-template.php:256
11 | 0.8024 | 4417288 | WP_Hook->apply_filters( $value = '', $args = [0 => ''] ) | .../plugin.php:205
12 | 1.4206 | 4442976 | capital_P_dangit( $text = NULL ) | .../class-wp-hook.php:324
13 | 1.4206 | 4443488 | str_replace( $search = [0  => ' Wordpress', 1 => '&#8216;Wordpress', 2 =>  '&#171;Wordpress', 3 => '>Wordpress', 4 => '(Wordpress'], $replace = [0  => ' WordPress', 1 => '&#8216;WordPress', 2 =>  '&#171;WordPress', 3 => '>WordPress', 4 => '(WordPress'], $subject = NULL ) | .../formatting.php:5708

</font>Call Stack
#	Time	Memory	Function	Location
1	0.0294	362376	{main}( )	.../index.php:0
2	0.0418	362760	require( '/var/www/html/kigl.site/wp-blog-header.php )	.../index.php:17
3	0.7501	3838992	require_once( '/var/www/html/kigl.site/wp-includes/template-loader.php )	.../wp-blog-header.php:19
4	0.7567	3906696	include( '/var/www/html/kigl.site/wp-content/themes/ptibogxivtheme-8.0.0/page.php )	.../template-loader.php:106
5	0.7999	4400296	get_template_part( $slug = 'loops/content', $name = 'page', $args = ??? )	.../page.php:24
6	0.7999	4400664	locate_template( $template_names = [0 => 'loops/content-page.php', 1 => 'loops/content.php'], $load = TRUE, $load_once = FALSE, $args = [] )	.../general-template.php:206
7	0.8001	4400776	load_template( $_template_file = '/var/www/html/kigl.site/wp-content/themes/ptibogxivtheme-8.0.0/loops/content-page.php', $load_once = FALSE, $args = [] )	.../template.php:745
8	0.8006	4401304	require( '/var/www/html/kigl.site/wp-content/themes/ptibogxivtheme-8.0.0/loops/content-page.php )	.../template.php:812
9	0.8022	4417008	the_content( $more_link_text = ???, $strip_teaser = ??? )	.../content-page.php:12
10	0.8024	4417040	apply_filters( $hook_name = 'the_content', $value = '' )	.../post-template.php:256
11	0.8024	4417288	WP_Hook->apply_filters( $value = '', $args = [0 => ''] )	.../plugin.php:205
12	1.4206	4442976	capital_P_dangit( $text = NULL )	.../class-wp-hook.php:324
13	1.4206	4443488	[str_replace](http://www.php.net/function.str-replace)( $search = [0 => ' Wordpress', 1 => '&#8216;Wordpress', 2 => '&#171;Wordpress', 3 => '>Wordpress', 4 => '(Wordpress'], $replace = [0 => ' WordPress', 1 => '&#8216;WordPress', 2 => '&#171;WordPress', 3 => '>WordPress', 4 => '(WordPress'], $subject = NULL )	.../formatting.php:5708


wp-debug log

System Debian 12.5

**Comment by ptibogxiv** [comment]
Please rename my theme folder with only ptibogxivtheme and not ptibogxivtheme-8.0.0 this name folder is not correct

**Comment by MatthewWeb** [comment]
<font size="1">
Deprecated: str_replace(): Passing null to parameter #3 ($subject) of  type array\|string is deprecated in  /var/www/html/kigl.site/wp-includes/formatting.php on line 5708
--


1 | 0.0000 | 376824 | {main}(  ) | .../index.php:0
2 | 0.0001 | 377128 | require( '/var/www/html/kigl.site/wp-blog-header.php ) | .../index.php:17
3 | 0.0879 | 4029488 | require_once( '/var/www/html/kigl.site/wp-includes/template-loader.php ) | .../wp-blog-header.php:19
4 | 0.0889 | 4052440 | include( '/var/www/html/kigl.site/wp-content/themes/ptibogxivtheme/page.php ) | .../template-loader.php:106
5 | 0.1107 | 4570296 | get_template_part( $slug = 'loops/content', $name = 'page', $args = ??? ) | .../page.php:24
6 | 0.1107 | 4570664 | locate_template( $template_names = [0 => 'loops/content-page.php', 1 => 'loops/content.php'], $load = TRUE, $load_once = FALSE, $args = [] ) | .../general-template.php:206
7 | 0.1107 | 4570776 | load_template( $_template_file = '/var/www/html/kigl.site/wp-content/themes/ptibogxivtheme/loops/content-page.php', $load_once = FALSE, $args = [] ) | .../template.php:745
8 | 0.1107 | 4571192 | require( '/var/www/html/kigl.site/wp-content/themes/ptibogxivtheme/loops/content-page.php ) | .../template.php:812
9 | 0.1113 | 4576824 | the_content( $more_link_text = ???, $strip_teaser = ??? ) | .../content-page.php:12
10 | 0.1114 | 4576856 | apply_filters( $hook_name = 'the_content', $value = '' ) | .../post-template.php:256
11 | 0.1114 | 4577104 | WP_Hook->apply_filters( $value = '', $args = [0 => ''] ) | .../plugin.php:205
12 | 0.5707 | 4661600 | capital_P_dangit( $text = NULL ) | .../class-wp-hook.php:324
13 | 0.5708 | 4662112 | str_replace( $search = [0  => ' Wordpress', 1 => '&#8216;Wordpress', 2 =>  '&#171;Wordpress', 3 => '>Wordpress', 4 => '(Wordpress'], $replace = [0  => ' WordPress', 1 => '&#8216;WordPress', 2 =>  '&#171;WordPress', 3 => '>WordPress', 4 => '(WordPress'], $subject = NULL ) | .../formatting.php:5708

</font>Deprecated: str_replace(): Passing null to parameter #3 ($subject) of type array|string is deprecated in /var/www/html/kigl.site/wp-includes/formatting.php on line 5708
Call Stack
#	Time	Memory	Function	Location
1	0.0000	376824	{main}( )	.../index.php:0
2	0.0001	377128	require( '/var/www/html/kigl.site/wp-blog-header.php )	.../index.php:17
3	0.0879	4029488	require_once( '/var/www/html/kigl.site/wp-includes/template-loader.php )	.../wp-blog-header.php:19
4	0.0889	4052440	include( '/var/www/html/kigl.site/wp-content/themes/ptibogxivtheme/page.php )	.../template-loader.php:106
5	0.1107	4570296	get_template_part( $slug = 'loops/content', $name = 'page', $args = ??? )	.../page.php:24
6	0.1107	4570664	locate_template( $template_names = [0 => 'loops/content-page.php', 1 => 'loops/content.php'], $load = TRUE, $load_once = FALSE, $args = [] )	.../general-template.php:206
7	0.1107	4570776	load_template( $_template_file = '/var/www/html/kigl.site/wp-content/themes/ptibogxivtheme/loops/content-page.php', $load_once = FALSE, $args = [] )	.../template.php:745
8	0.1107	4571192	require( '/var/www/html/kigl.site/wp-content/themes/ptibogxivtheme/loops/content-page.php )	.../template.php:812
9	0.1113	4576824	the_content( $more_link_text = ???, $strip_teaser = ??? )	.../content-page.php:12
10	0.1114	4576856	apply_filters( $hook_name = 'the_content', $value = '' )	.../post-template.php:256
11	0.1114	4577104	WP_Hook->apply_filters( $value = '', $args = [0 => ''] )	.../plugin.php:205
12	0.5707	4661600	capital_P_dangit( $text = NULL )	.../class-wp-hook.php:324
13	0.5708	4662112	[str_replace](http://www.php.net/function.str-replace)( $search = [0 => ' Wordpress', 1 => '&#8216;Wordpress', 2 => '&#171;Wordpress', 3 => '>Wordpress', 4 => '(Wordpress'], $replace = [0 => ' WordPress', 1 => '&#8216;WordPress', 2 => '&#171;WordPress', 3 => '>WordPress', 4 => '(WordPress'], $subject = NULL )	.../formatting.php:5708

**Comment by MatthewWeb** [comment]
Installed hestiacp and your theme just worked. Apparently I don't know how to configure Apache. Thanks for a great product!

**Comment by MatthewWeb** [comment]
Found a problem with the configuration. The php settings line required is `short_open_tag = On`
